name: Building artifacts and load them to PYPI index
on:
  push:
    branches: [main]
    paths:
      - "VERSION.txt"

jobs:
  Build_release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Update pip and install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv
          python --version
          pip --version
          pipenv --version

      - name: Install python dependencies
        run: |
          cd ${{ github.workspace }} && ls
          pipenv install --dev
          pipenv run pip list --local

      - name: Build distribution archives
        run: pipenv run python3 -m build

      - name: Upload archieves to PYPI.org
        run: pipenv run python3 -m twine upload -u ${{ secrets.api_user }} -p ${{ secrets.api_token }} dist/*
